# Generated by Django 5.0.2 on 2024-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('phone_number_user', models.CharField(max_length=50, verbose_name='Телефон клиента')),
                ('callback_completed', models.BooleanField(default=False, verbose_name='Обратный звонок совершён')),
            ],
        ),
    ]
