# Generated by Django 5.0.2 on 2024-03-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Обратные звонки', 'verbose_name_plural': 'Обратный звонок'},
        ),
    ]
