# Generated by Django 5.0.2 on 2024-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0004_alter_orderforanonymoususer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='check_order',
            field=models.FileField(default=1, upload_to='checks', verbose_name='Чек'),
            preserve_default=False,
        ),
    ]
