# Generated by Django 5.0.2 on 2024-03-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0005_orderforanonymoususer_check_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='house_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='order_receving',
            field=models.CharField(choices=[('Самовывоз', 'Саммовывоз'), ('Доставка курьером', 'Доставка курьером')], default='Самовывоз', max_length=20, verbose_name='Способ получения заказа'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='street',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Улица / Переулок'),
        ),
    ]
