# Generated by Django 5.0.2 on 2024-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0006_orderforanonymoususer_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderforanonymoususer',
            name='name',
        ),
    ]
