# Generated by Django 5.0.2 on 2024-03-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0007_remove_orderforanonymoususer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderforanonymoususer',
            old_name='order_receving',
            new_name='order_receiving',
        ),
    ]
