# Generated by Django 5.0.2 on 2024-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0008_rename_order_receving_orderforanonymoususer_order_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderforanonymoususer',
            name='name_anonymous_user',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderforanonymoususer',
            name='order_receiving',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка курьером', 'Доставка курьером')], default='Самовывоз', max_length=20, verbose_name='Способ получения заказа'),
        ),
    ]
