# Generated by Django 5.0.2 on 2024-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_tasks', '0009_orderforanonymoususer_name_anonymous_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderforanonymoususer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, verbose_name='Номер телефона'),
        ),
    ]
