# Generated by Django 5.0.2 on 2024-02-21 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='Город')),
                ('house_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер дома')),
                ('street', models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер подъезда')),
                ('entrance_number', models.CharField(blank=True, max_length=2, null=True, verbose_name='Номер подъезда')),
                ('apartment_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер квартиры')),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Почтовый индекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user'],
            },
        ),
    ]
