# Generated by Django 5.0.2 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countitemproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='main.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='product',
            name='countitemproduct',
            field=models.ManyToManyField(blank=True, null=True, to='main.countitemproduct', verbose_name='Количество товара'),
        ),
    ]
