# Generated by Django 5.0.2 on 2024-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='articles_images', verbose_name='Изображение'),
        ),
    ]
