# Generated by Django 5.0.2 on 2024-02-09 01:03

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Вид животного')),
                ('image', models.ImageField(upload_to='animals')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название акции')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент')),
                ('start_sale', models.DateTimeField(verbose_name='Время начала акции')),
                ('stop_sale', models.DateTimeField(verbose_name='Время окончания акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(upload_to='articles_images', verbose_name='Изображение')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.CharField(max_length=255, verbose_name='Время чтения')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animal', verbose_name='Животные')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя бренда')),
                ('image', models.ImageField(upload_to='brands_images', verbose_name='Изображение')),
                ('animal', models.ManyToManyField(to='main.animal')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('animal', models.ManyToManyField(to='main.animal', verbose_name='Животное')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoryproduct', verbose_name='Имя родительсокй категории')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='PayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
                ('cvc', models.PositiveIntegerField(verbose_name='CVC')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Баланс на карте')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('check_order', models.FileField(upload_to='cheks', verbose_name='Чек')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('pay_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paycard', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название продукта')),
                ('image_prev', models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Обязательное изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена товара за единицу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('key_features', models.TextField(blank=True, null=True, verbose_name='Ключевые особенности')),
                ('compound', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('guaranteed_analysis', models.TextField(blank=True, null=True, verbose_name='Гарантированный анализ')),
                ('nutritional_supplements', models.TextField(blank=True, null=True, verbose_name='Пищевые добавки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='Бренд товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryproduct', verbose_name='Категория продукта')),
                ('order', models.ManyToManyField(to='main.order', verbose_name='Заказ')),
                ('sale', models.ManyToManyField(to='main.sale', verbose_name='Товар на акции')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images', verbose_name='Изображение продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
        migrations.CreateModel(
            name='CountItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент от стоимости единицы товара')),
                ('unit', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('value', models.FloatField(verbose_name='Количество массы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Количество товара',
                'verbose_name_plural': 'Количество товара',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pet', models.CharField(max_length=255, verbose_name='Kличка питомца')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
