# Generated by Django 5.0.2 on 2024-02-13 16:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
    ]
