# Generated by Django 5.0.2 on 2024-02-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_animal_sale_article_brand_categoryproduct_paycard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Баланс на карте'),
        ),
    ]
