# Generated by Django 5.0.2 on 2024-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_countitemproduct_product_remove_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(default='2024-02-04 18:00:45.616745+00:00'),
        ),
    ]
