# Generated by Django 5.0.2 on 2024-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
