# Generated by Django 5.0.2 on 2024-02-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_image_prev'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(verbose_name='Статус')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.statusorder', verbose_name='Статус заказа'),
            preserve_default=False,
        ),
    ]
