# Generated by Django 5.0.2 on 2024-02-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycard',
            name='expiration_date',
            field=models.CharField(default='', max_length=5, verbose_name='Дата окончания срока действия карты'),
        ),
    ]
