# Generated by Django 5.0.2 on 2024-02-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_order_remove_product_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='animal',
        ),
        migrations.AddField(
            model_name='product',
            name='animal',
            field=models.ManyToManyField(to='main.animal', verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='review',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.RemoveField(
            model_name='countitemproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sale', verbose_name='Товар на акции'),
        ),
        migrations.AddField(
            model_name='countitemproduct',
            name='product',
            field=models.ManyToManyField(to='main.product', verbose_name='Продукт'),
        ),
    ]
