# Generated by Django 5.0.2 on 2024-02-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paycard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.paycard', verbose_name='Карта'),
        ),
    ]
