# Generated by Django 5.0.2 on 2024-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_pay_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleForOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='check_order',
            field=models.FileField(upload_to='checks', verbose_name='Чек'),
        ),
    ]
