# Generated by Django 5.0.2 on 2024-02-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_statusorder_statusesorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countitemproduct',
        ),
        migrations.AddField(
            model_name='countitemproduct',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество продукта'),
        ),
        migrations.AddField(
            model_name='countitemproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
