# Generated by Django 5.0.2 on 2024-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_countitemproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_order',
        ),
        migrations.AlterModelOptions(
            name='countitemproduct',
            options={'ordering': ['product'], 'verbose_name': 'Количество товара', 'verbose_name_plural': 'Количество товара'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Оформлен', 'Оформлен'), ('Ожидает оплату', 'Ожидает оплату'), ('Оплачен', 'Оплачен'), ('Подтвержден', 'Подтвержден'), ('Выполнен', 'Выполнен'), ('Аннулирован', 'Аннулирован'), ('Ошибка оплаты', 'Ошибка оплаты')], default='Оформлен', max_length=15),
        ),
        migrations.AlterField(
            model_name='countitemproduct',
            name='unit',
            field=models.CharField(choices=[('л', 'л'), ('кг', 'кг'), ('шт', 'шт')], max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.DeleteModel(
            name='StatusesOrder',
        ),
    ]
