# Generated by Django 5.0.2 on 2024-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articlefororders_alter_order_check_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countitemproduct',
            options={'ordering': ['value'], 'verbose_name': 'Количество товара', 'verbose_name_plural': 'Количество товара'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Сколько раз продан'),
        ),
    ]
