# Generated by Django 5.0.2 on 2024-02-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_order_show_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefororders',
            name='article',
            field=models.CharField(max_length=15, verbose_name='Номер заказа'),
        ),
    ]
