# Generated by Django 5.0.2 on 2024-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_order_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
