# Generated by Django 5.0.2 on 2024-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=16, verbose_name='Номер заказа'),
        ),
    ]
