# Generated by Django 5.0.2 on 2024-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_articlefororders_letter_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=40, null=True, verbose_name='Улица / Переулок')),
                ('house_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_receving',
            field=models.CharField(choices=[('Самовывоз', 'Саммовывоз'), ('Доставка курьером', 'Доставка курьером')], default='Самовывоз', max_length=20, verbose_name='Способ получения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Улица / Переулок'),
        ),
    ]
