# Generated by Django 5.0.2 on 2024-03-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_store_order_apartment_number_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_receving',
            new_name='order_receiving',
        ),
    ]
