# Generated by Django 5.0.2 on 2024-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_order_receving_order_order_receiving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_receiving',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка курьером', 'Доставка курьером')], default='Самовывоз', max_length=20, verbose_name='Способ получения заказа'),
        ),
    ]
