# Generated by Django 5.0.2 on 2024-02-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetErrorDataApiV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=1500, unique=True, verbose_name='Название URL')),
                ('model_name', models.CharField(max_length=1500, verbose_name='Название Модели')),
                ('section_error', models.TextField(verbose_name='Блок создания ошибки')),
                ('error_status_code', models.IntegerField(default=0, verbose_name='Блок изменения статус кода')),
                ('theme', models.CharField(max_length=2000, verbose_name='Тема занятия')),
                ('lesson_number', models.CharField(max_length=2000, verbose_name='Номер занятия')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус применения')),
                ('description', models.TextField(default='123', verbose_name='Описание генерируемой ошибки')),
            ],
            options={
                'verbose_name': 'Объект моделирования функциональных ситуации REST API',
                'verbose_name_plural': 'Объекты моделирования функциональных ситуаций REST API',
            },
        ),
        migrations.CreateModel(
            name='SetErrorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id_tag_a', models.CharField(help_text='Выберите из элемента a в HTML на странице значение атрибута id', max_length=255, verbose_name="ID HTML тег <a id='ид элемента' ></a> разметки")),
                ('href', models.TextField(verbose_name='Атрибут:значение ссылка')),
                ('page_name', models.CharField(max_length=500, verbose_name='Название страницы')),
                ('section_of_page', models.CharField(max_length=500, verbose_name='Блок где будет ошибка')),
                ('theme', models.CharField(max_length=2000, verbose_name='Тема занятия')),
                ('lesson_number', models.CharField(max_length=2000, verbose_name='Номер занятия')),
                ('is_active', models.BooleanField(verbose_name='Статус применения')),
                ('description', models.TextField(verbose_name='Описание генерируемой ошибки')),
            ],
            options={
                'verbose_name': 'Объект моделирования функциональных ситуации Links',
                'verbose_name_plural': 'Объекты моделирования функциональных ситуаций Links',
            },
        ),
        migrations.CreateModel(
            name='StyledComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_class_name', models.CharField(help_text='Выберите из элемента HTML на странице значение атрибута class', max_length=255, verbose_name='CSS class элемента HTML разметки')),
                ('style', models.TextField(verbose_name='Атрибут:значение CSS')),
                ('page_name', models.CharField(max_length=500, verbose_name='Название страницы')),
                ('section_of_page', models.CharField(max_length=500, verbose_name='Блок где будет ошибка')),
                ('theme', models.CharField(max_length=2000, verbose_name='Тема занятия')),
                ('lesson_number', models.CharField(max_length=2000, verbose_name='Номер занятия')),
                ('is_active', models.BooleanField(verbose_name='Статус применения')),
                ('description', models.TextField(verbose_name='Описание генерируемой ошибки')),
            ],
            options={
                'verbose_name': 'Объект моделирования ситуации HTML CSS',
                'verbose_name_plural': 'Объекты моделирования ситуаций HTML CSS',
            },
        ),
    ]
