# Generated by Django 5.0.2 on 2024-02-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyledComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_class_name', models.CharField(help_text='Выберите из элемента HTML на странице значение атрибута class', max_length=255, verbose_name='CSS class элемента HTML разметки')),
                ('style', models.TextField(verbose_name='Атрибут:значение CSS')),
                ('page_name', models.CharField(max_length=500, verbose_name='Название страницы')),
                ('section_of_page', models.CharField(max_length=500, verbose_name='Блок где будет ошибка')),
                ('theme', models.CharField(max_length=2000, verbose_name='Тема занятия')),
                ('lesson_number', models.CharField(max_length=2000, verbose_name='Номер занятия')),
                ('is_active', models.BooleanField(verbose_name='Статус применения')),
                ('description', models.TextField(verbose_name='Описание генерируемой ошибки')),
            ],
            options={
                'verbose_name': 'Объект моделирования ситуации',
                'verbose_name_plural': 'Объекты моделирования ситуаций',
            },
        ),
    ]
