# Generated by Django 5.0.2 on 2024-02-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seterrordataapiv1',
            name='error_status_code',
            field=models.CharField(default='200', max_length=3, verbose_name='Блок изменения статус кода'),
        ),
    ]
