# Generated by Django 5.0.2 on 2024-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetErrorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id_tag_a', models.CharField(help_text='Выберите из элемента a в HTML на странице значение атрибута id', max_length=255, verbose_name="ID HTML тег <a id='ид элемента' ></a> разметки")),
                ('href', models.TextField(verbose_name='Атрибут:значение ссылка')),
                ('page_name', models.CharField(max_length=500, verbose_name='Название страницы')),
                ('section_of_page', models.CharField(max_length=500, verbose_name='Блок где будет ошибка')),
                ('theme', models.CharField(max_length=2000, verbose_name='Тема занятия')),
                ('lesson_number', models.CharField(max_length=2000, verbose_name='Номер занятия')),
                ('is_active', models.BooleanField(verbose_name='Статус применения')),
                ('description', models.TextField(verbose_name='Описание генерируемой ошибки')),
            ],
            options={
                'verbose_name': 'Объект моделирования функциональных ситуации',
                'verbose_name_plural': 'Объекты моделирования функциональных ситуаций',
            },
        ),
    ]
