# Generated by Django 5.0.2 on 2024-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management', '0002_seterrorlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetErrorDataApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='seterrorlink',
            options={'verbose_name': 'Объект моделирования функциональных ситуации Links', 'verbose_name_plural': 'Объекты моделирования функциональных ситуаций Links'},
        ),
        migrations.AlterModelOptions(
            name='styledcomponents',
            options={'verbose_name': 'Объект моделирования ситуации HTML CSS', 'verbose_name_plural': 'Объекты моделирования ситуаций HTML CSS'},
        ),
    ]
