# Generated by Django 5.0.2 on 2024-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management', '0002_seterrordataapiv1_error_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seterrordataapiv1',
            name='error_status_code',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Блок изменения статус кода'),
        ),
    ]
