# Generated by Django 5.0.2 on 2024-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management', '0002_seterrorlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetErrorDataApiV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=1500, verbose_name='Название URL')),
                ('model_name', models.CharField(max_length=1500, verbose_name='Название Модели')),
                ('section_error', models.TextField(verbose_name='Блок создания ошибки')),
                ('theme', models.CharField(max_length=2000, verbose_name='Тема занятия')),
                ('lesson_number', models.CharField(max_length=2000, verbose_name='Номер занятия')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус применения')),
                ('description', models.TextField(default='123', verbose_name='Описание генерируемой ошибки')),
            ],
            options={
                'verbose_name': 'Объект моделирования функциональных ситуации REST API',
                'verbose_name_plural': 'Объекты моделирования функциональных ситуаций REST API',
            },
        ),
        migrations.AlterModelOptions(
            name='seterrorlink',
            options={'verbose_name': 'Объект моделирования функциональных ситуации Links', 'verbose_name_plural': 'Объекты моделирования функциональных ситуаций Links'},
        ),
        migrations.AlterModelOptions(
            name='styledcomponents',
            options={'verbose_name': 'Объект моделирования ситуации HTML CSS', 'verbose_name_plural': 'Объекты моделирования ситуаций HTML CSS'},
        ),
    ]
