# Generated by Django 5.0.2 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management', '0003_alter_seterrordataapiv1_error_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seterrordataapiv1',
            name='error_status_code',
            field=models.IntegerField(default=0, verbose_name='Блок изменения статус кода'),
        ),
    ]
